### ISSUE TITLE
Update in asdf-plugins.

### ISSUE THREAD

**Issue by vic** [asdf-community/asdf-elm#1]
Hi @imbsky, nice work! 

Would you mind updating asdf-plugins repo and set `asdf-community/asdf-elm` as default?

I'll archive https://github.com/vic/asdf-elm after that :)

Kudos!

**Comment by imbsky** [comment]
Thanks, If you okay, I will do that 😁

**Comment by vic** [comment]
Yes, please :)

**Comment by imbsky** [comment]
Done!
