### ISSUE TITLE
Elm 0.19.1 fails to install due to upstream release naming convention shift

### ISSUE THREAD

**Issue by arubis** [asdf-community/asdf-elm#11]
`asdf-elm` attempts to install Elm from a URL that matches the release naming convention used through 0.19.0, but not published at 0.19.1:

```
> asdf install elm 0.19.1
https://github.com/elm/compiler/releases/download/0.19.1/binaries-for-mac.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error fetching https://github.com/elm/compiler/releases/download/0.19.1/binaries-for-mac.tar.gz
```

Actual releases from 0.19.1 forward (as seen on https://github.com/elm/compiler/releases/tag/0.19.1) use the naming convention `binary-for-(platform)-64-bit.gz`

Previously reported at https://github.com/vic/asdf-elm/issues/9#issuecomment-544759468 with suggested fix at https://github.com/vic/asdf-elm/pull/11 (pulls in https://github.com/xorphar/asdf-elm/tree/gz64bit-binary).

**Comment by imbsky** [comment]
The latest version seems to work correctly. Try updating the plugin.

**Comment by imbsky** [comment]
and if you could provide information about your environment, it would be helpful.

**Comment by arubis** [comment]
Oh, interesting--root cause was completely different than I'd expected.

`asdf plugin update` won't catch if the git repo associated with a plugin has been changed. I had an older install, so this was the prior state:

```
 ~/.asdf/plugins/elm (master)> git remote --verbose
origin  git@github.com:vic/asdf-elm.git (fetch)
origin  git@github.com:vic/asdf-elm.git (push)
```

Doing an `asdf plugin remove elm; asdf plugin add elm; asdf install elm 0.19.1` worked fine. :+1:

**Comment by imbsky** [comment]
Great!

**Comment by arubis** [comment]
Not an issue on this repo, then; I'll close the issue.

In your opinion, is this something worth filing against asdf-vm/asdf itself? A stuck plugin isn't what I'd consider expected behavior, but on the other hand, having a repo change out from under you while still in use sounds like a huge potential vulnerability.

**Comment by imbsky** [comment]
Yeah, I think that's not a bad idea, but I don't have a good approach to it at this point.
