### ISSUE TITLE
Apple Silicon not supported

### ISSUE THREAD

**Issue by AlphaHydrae** [asdf-community/asdf-elm#18]
Elm installation fails with the message "Unsupported architecture":

```
$> asdf install elm 0.19.1
\e[31mFail:\e[m Unsupported architecture

$> asdf --version
v0.8.1

$> asdf plugin list --refs --urls
elm   https://github.com/asdf-community/asdf-elm.git master e55a282

$> uname -a
Darwin MyComputer.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64

$> sysctl -n machdep.cpu.brand_string
Apple M1
```

Hardware: MacBook Pro 13-inch, M1, 2020
Operating system: macOS Big Sur 11.4

**Comment by brianvanburken** [comment]
Hi @AlphaHydrae thank you for reporting the issue. Since I don't have a M1 device, can you verify that the "installer-for-mac.pkg" (downloadable here https://github.com/elm/compiler/releases/tag/0.19.1) is able to be install on a M1 device?

**Comment by AlphaHydrae** [comment]
Hi @brianvanburken. Thanks for the quick response.

I have successfully installed Elm manually with this installer, and verified that at least the REPL works:

```bash
$> /usr/local/bin/elm repl  
---- Elm 0.19.1 ----------------------------------------------------------------
Say :help for help and :exit to exit! More at <https://elm-lang.org/0.19.1/repl>
--------------------------------------------------------------------------------
> 1 + 2
3 : number
```

**Comment by brianvanburken** [comment]
Awesome! Could you send me the result from running `uname -m` in the terminal?

**Comment by AlphaHydrae** [comment]
> Awesome! Could you send me the result from running `uname -m` in the terminal?

```bash
$> uname -m
arm64
```

**Comment by brianvanburken** [comment]
@AlphaHydrae I think the 64bit binaries will also run on your mac using Rosetta2. I've created a commit on my fork which adds the support for `arm64` architecture for 0.19.0 and above. Could you test this for me and tell me if the fix works correctly? If so, I'll push the fix to asdf-elm.

Steps to switch to my fork:
```
asdf plugin-remove elm
asdf plugin-add elm https://github.com/brianvanburken/asdf-elm
asdf install elm 0.19.1
```

Steps to switch back to official plugin:
```
asdf plugin-remove elm
asdf plugin-add elm
```

**Comment by AlphaHydrae** [comment]
@brianvanburken It seems to work just fine:

```bash
$> asdf plugin remove elm
$> asdf plugin-add elm https://github.com/brianvanburken/asdf-elm
$> asdf install elm 0.19.1
∗ Downloading and installing elm...
The installation was successful!

$> asdf global elm 0.19.1
$> which elm
~/.asdf/shims/elm

$> elm --version
0.19.1

$> elm repl
---- Elm 0.19.1 ----------------------------------------------------------------
Say :help for help and :exit to exit! More at <https://elm-lang.org/0.19.1/repl>
--------------------------------------------------------------------------------
> 1 + 2
3 : number
>
```

**Comment by brianvanburken** [comment]
Awesome! @AlphaHydrae thank you very much for your support. I've pushed the commit with support for M1 chips. You can now switch back to the official plugin

**Comment by AlphaHydrae** [comment]
You're welcome @brianvanburken. I've just confirmed that it works the same with the official plugin. Thanks a lot for the fix!
